- name: checkout anyenv_repo for system
  git:
    repo: "{{ anyenv.git_url }}"
    dest: "{{ anyenv.install_dir }}"

- name: add anyenv initialization
  template:
    src: anyenv.sh.j2
    dest: /etc/profile.d/anyenv.sh
    owner: root
    group: root
    mode: 0755
  become: yes
