anyenv:
  git_url: https://github.com/riywo/anyenv
  install_dir:  ~/.anyenv

kerl:
  git_url: https://raw.githubusercontent.com/kerl/kerl/master/kerl
  install_dir:  ~/kerl

anyenv_rbenv_version: 2.3.1
anyenv_erlenv_version: 19.1
anyenv_exenv_version: 1.3.4
