- name: ndenv installed?
  stat:
    path: "{{ anyenv.install_dir }}/envs/ndenv"
  register: ndenv_installed

- name: install ndenv
  shell: bash -lc "anyenv install ndenv"
  when: not ndenv_installed.stat.exists

- name: node installed?
  shell: bash -lc "ndenv global"
  register: ndenv_global_version
  changed_when: false

- name: install node
  shell: bash -lc "ndenv install {{ ndenv_version }}"
  when: ndenv_global_version.stdout == "system"

- name: global node
  shell: bash -lc "ndenv global {{ ndenv_version }}"
  when: ndenv_global_version.stdout == "system"
