- name: exenv installed?
  stat:
    path: "{{ anyenv.install_dir }}/envs/exenv"
  register: exenv_installed

- name: install exenv
  shell: bash -lc "anyenv install exenv"
  when: not exenv_installed.stat.exists

- name: elixir installed?
  shell: bash -lc "exenv global"
  register: exenv_global_version
  changed_when: false

- name: install elixir
  shell: bash -lc "exenv install {{ exenv_version }}"
  when: exenv_global_version.stdout == "system"

- name: global elixir
  shell: bash -lc "exenv global {{ exenv_version }}"
  when: exenv_global_version.stdout == "system"
